/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoraGastos;

/**
 *
 * @author andre
 */
public class InterfaceEnergia extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceCombustivel
     */
    public InterfaceEnergia() {
        initComponents();
        
        setResizable(false);
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonHome = new javax.swing.JButton();
        buttonEnergia = new javax.swing.JButton();
        buttonCombustivel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        fieldDias = new javax.swing.JTextField();
        labelDias = new javax.swing.JLabel();
        fieldWatts = new javax.swing.JTextField();
        labelWatts = new javax.swing.JLabel();
        fieldHoras = new javax.swing.JTextField();
        labelHoras = new javax.swing.JLabel();
        fieldCustoKwh = new javax.swing.JTextField();
        labelCustoKwh = new javax.swing.JLabel();
        btnCalc = new javax.swing.JButton();
        fieldResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1041, 625));
        setMinimumSize(new java.awt.Dimension(1041, 625));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1041, 625));
        jPanel1.setMinimumSize(new java.awt.Dimension(1041, 625));
        jPanel1.setPreferredSize(new java.awt.Dimension(1041, 625));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(16, 15, 16));
        jPanel2.setAutoscrolls(true);
        jPanel2.setMinimumSize(new java.awt.Dimension(240, 625));
        jPanel2.setPreferredSize(new java.awt.Dimension(240, 625));
        jPanel2.setVerifyInputWhenFocusTarget(false);

        buttonHome.setBackground(new java.awt.Color(16, 15, 16));
        buttonHome.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        buttonHome.setForeground(new java.awt.Color(255, 255, 255));
        buttonHome.setText("Home");
        buttonHome.setBorder(null);
        buttonHome.setBorderPainted(false);
        buttonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHomeMouseClicked(evt);
            }
        });
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });

        buttonEnergia.setBackground(new java.awt.Color(16, 15, 16));
        buttonEnergia.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        buttonEnergia.setForeground(new java.awt.Color(255, 255, 255));
        buttonEnergia.setText("Energia");
        buttonEnergia.setBorder(null);
        buttonEnergia.setBorderPainted(false);
        buttonEnergia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEnergiaMouseClicked(evt);
            }
        });
        buttonEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnergiaActionPerformed(evt);
            }
        });

        buttonCombustivel.setBackground(new java.awt.Color(16, 15, 16));
        buttonCombustivel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        buttonCombustivel.setForeground(new java.awt.Color(255, 255, 255));
        buttonCombustivel.setText("Combustivel");
        buttonCombustivel.setBorderPainted(false);
        buttonCombustivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCombustivelMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonCombustivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonEnergia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(109, 109, 109)
                .addComponent(buttonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 169;
        gridBagConstraints.ipady = 333;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(36, 36, 36));
        jPanel3.setMaximumSize(new java.awt.Dimension(816, 625));
        jPanel3.setMinimumSize(new java.awt.Dimension(816, 625));
        jPanel3.setPreferredSize(new java.awt.Dimension(816, 625));

        fieldDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDiasActionPerformed(evt);
            }
        });

        labelDias.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        labelDias.setForeground(new java.awt.Color(255, 255, 255));
        labelDias.setText("Tota de Dias de Uso");

        labelWatts.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        labelWatts.setForeground(new java.awt.Color(255, 255, 255));
        labelWatts.setText("Watts do Aparelho");

        labelHoras.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        labelHoras.setForeground(new java.awt.Color(255, 255, 255));
        labelHoras.setText("Horas de Uso por Dia");

        labelCustoKwh.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        labelCustoKwh.setForeground(new java.awt.Color(255, 255, 255));
        labelCustoKwh.setText("Valor do kWh na Sua Região");

        btnCalc.setText("Calcular");
        btnCalc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcMouseClicked(evt);
            }
        });
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        fieldResultado.setColumns(20);
        fieldResultado.setRows(5);
        fieldResultado.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCalc)
                        .addComponent(fieldDias)
                        .addComponent(labelDias, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelWatts, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldWatts)
                        .addComponent(labelHoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldHoras)
                        .addComponent(labelCustoKwh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldCustoKwh)))
                .addContainerGap(567, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelDias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(labelWatts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldWatts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(labelHoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(labelCustoKwh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCustoKwh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnCalc)
                .addGap(37, 37, 37)
                .addComponent(fieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 277;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonHomeActionPerformed

    private void fieldDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDiasActionPerformed

    private void btnCalcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcMouseClicked
        
    }//GEN-LAST:event_btnCalcMouseClicked

    private void buttonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHomeMouseClicked
        InterfaceHome homeInterface = new InterfaceHome();
        homeInterface.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonHomeMouseClicked

    private void buttonEnergiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEnergiaMouseClicked
        InterfaceEnergia energiaInterface = new InterfaceEnergia();
        energiaInterface.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonEnergiaMouseClicked

    private void buttonEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnergiaActionPerformed
       
    }//GEN-LAST:event_buttonEnergiaActionPerformed

    private void buttonCombustivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCombustivelMouseClicked
        InterfaceCombustivel combustivelInterface = new InterfaceCombustivel();
        combustivelInterface.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonCombustivelMouseClicked

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        String diasUso = fieldDias.getText();
        String horasUso = fieldHoras.getText();
        String wattsAparelho = fieldWatts.getText();
        String custoKwh = fieldCustoKwh.getText();
        
        float valorDias = Float.parseFloat(diasUso);
        float valorHoras = Float.parseFloat(horasUso);
        float valorWatts = Float.parseFloat(wattsAparelho);
        float valorKwh = Float.parseFloat(custoKwh);
        
        Energia energia = new Energia();
        
        float resultado = energia.Calcular(valorDias, valorHoras, valorWatts, valorKwh);
        fieldResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btnCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceEnergia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceEnergia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceEnergia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceEnergia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceEnergia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton buttonCombustivel;
    private javax.swing.JButton buttonEnergia;
    private javax.swing.JButton buttonHome;
    private javax.swing.JTextField fieldCustoKwh;
    private javax.swing.JTextField fieldDias;
    private javax.swing.JTextField fieldHoras;
    private javax.swing.JTextArea fieldResultado;
    private javax.swing.JTextField fieldWatts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelCustoKwh;
    private javax.swing.JLabel labelDias;
    private javax.swing.JLabel labelHoras;
    private javax.swing.JLabel labelWatts;
    // End of variables declaration//GEN-END:variables
}
